FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

ARG VITE_ENABLE_WORKER=true
ENV VITE_ENABLE_WORKER=${VITE_ENABLE_WORKER}

STUFF GOES HERE

FROM nginx:1.25-alpine
TODO COPY nginx.conf in place
TODO COPY results from /app/dist to html location in nginx

TODO publish port 80

CMD ["nginx", "-g", "daemon off;"]
