FROM python:3.11-slim AS base

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    SQLITE_PATH=/data/tasks.db

RUN mkdir -p /data

STUFF GOES HERE

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
